Team-Catxi/Catxi_BackEnd

- src/main/java/com/project/catxi/common/api/ApiResponse.java
- src/main/java/com/project/catxi/common/api/CommonPageResponse.java
- src/main/java/com/project/catxi/common/api/error/CommonErrorCode.java
- src/main/java/com/project/catxi/common/api/error/ErrorCode.java
- src/main/java/com/project/catxi/common/api/exception/CatxiException.java
- src/main/java/com/project/catxi/common/api/handler/ExceptionAdvice.java
- src/main/java/com/project/catxi/common/api/success/CommonSuccessCode.java
- src/main/java/com/project/catxi/common/api/success/SuccessCode.java
> [FEAT] 공통예외처리세팅

- .gitignore
- src/main/java/com/project/catxi/chat/domain/ChatMessage.java
- src/main/java/com/project/catxi/chat/domain/ChatParticipant.java
- src/main/java/com/project/catxi/chat/domain/ChatRoom.java
- src/main/java/com/project/catxi/common/domain/BaseTimeEntity.java
- src/main/java/com/project/catxi/common/domain/Location.java
- src/main/java/com/project/catxi/common/domain/MessageType.java
- src/main/java/com/project/catxi/common/domain/RoomStatus.java
- src/main/java/com/project/catxi/member/domain/MatchHistory.java
- src/main/java/com/project/catxi/member/domain/Member.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
> [FEAT] 도메인 1차 세팅

- src/main/resources/application-dev.yml
- src/main/resources/application.yml
#9 
application.yml과 application-dev.yml을 분리하여 로컬 테스트/배포 환경을 분리하였습니다.
>
> [FEAT] DB 환경 분리

- src/main/java/com/project/catxi/chat/domain/ChatParticipant.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
> [BUG] ChatParticipant isActive 필드명 변경

- Dockerfile
- build.gradle
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
#7 
- 젠킨스에서는 빌드만 해주고 그 빌드 JAR 파일을 EC2 서버로 보내서 배포환경 구축
- 현재 배포까지는 정상적으로 동작하고 github와 jenkins 웹훅 연결을 통해서 디스코드에 빌드 성공 시 알림 전송
- Nginx 정상 작동 아직 테스트 해보지 않음
- 컨트롤러에서 오류가 더 이상 발생하지 않고 정상적으로 배포 환경이 동작하면 로드 밸런싱 꼭! 테스트해보기
- 도커파일은 만들어두었지만 이번에는 짧은 시간 상 도커를 사용하여 배포를 이용하지 않았지만 추후 추가 개발이 진행된다면 도커 사용해보기
> [FEAT] Dockerfile 설정

- src/main/java/com/project/catxi/common/domain/Location.java
> [REFACT] Location : 정문 -> 다솔관 변경

- src/main/java/com/project/catxi/chat/config/StompHandler.java
- src/main/java/com/project/catxi/chat/controller/ChatController.java
- src/main/java/com/project/catxi/chat/dto/ChatMessageSendReq.java
- src/main/java/com/project/catxi/chat/service/ChatMessageService.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/chat/service/RedisPubSubService.java
> [REFACT] 이메일 기반 사용자 식별로 구조 개선

- src/main/java/com/project/catxi/chat/controller/ChatController.java
- src/main/java/com/project/catxi/chat/dto/KickRequest.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/common/api/error/ChatRoomErrorCode.java
> [FEAT] 강퇴하기 api 구현

- src/main/java/com/project/catxi/chat/domain/ChatRoom.java
> [FIX] ChatRoom 엔티티 matchedAt 필드 nullable=true로 변경

- src/main/java/com/project/catxi/chat/controller/SseController.java
- src/main/java/com/project/catxi/chat/domain/ChatRoom.java
- src/main/java/com/project/catxi/chat/dto/SseSendReq.java
- src/main/java/com/project/catxi/chat/dto/SseSendRes.java
- src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/chat/service/ReadyService.java
- src/main/java/com/project/catxi/chat/service/SseService.java
- src/main/java/com/project/catxi/chat/service/SseSubscriber.java
- src/main/java/com/project/catxi/chat/service/TimerService.java
- src/main/java/com/project/catxi/common/api/error/ChatParticipantErrorCode.java
- src/main/java/com/project/catxi/common/api/error/ChatRoomErrorCode.java
- src/main/java/com/project/catxi/common/api/error/SseErrorCode.java
- src/main/java/com/project/catxi/common/config/RedisConfig.java
- src/main/java/com/project/catxi/common/config/SecurityConfig.java
- src/main/java/com/project/catxi/common/config/SseAuthenticationFilter.java
> [FEAT] Sse Ready Service SecurityFilter 추가

- src/main/java/com/project/catxi/chat/controller/SseController.java
- src/main/java/com/project/catxi/chat/domain/ChatRoom.java
- src/main/java/com/project/catxi/chat/dto/SseSendReq.java
- src/main/java/com/project/catxi/chat/dto/SseSendRes.java
- src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/chat/service/ReadyService.java
- src/main/java/com/project/catxi/chat/service/SseService.java
- src/main/java/com/project/catxi/chat/service/SseSubscriber.java
- src/main/java/com/project/catxi/chat/service/TimerService.java
- src/main/java/com/project/catxi/common/api/error/ChatParticipantErrorCode.java
- src/main/java/com/project/catxi/common/api/error/ChatRoomErrorCode.java
- src/main/java/com/project/catxi/common/api/error/SseErrorCode.java
- src/main/java/com/project/catxi/common/config/RedisConfig.java
- src/main/java/com/project/catxi/common/config/SecurityConfig.java
- src/main/java/com/project/catxi/common/config/SseAuthenticationFilter.java
> [FEAT] Sse Ready Service SecurityFilter

- src/main/java/com/project/catxi/chat/controller/ChatController.java
- src/main/java/com/project/catxi/chat/dto/ChatRoomInfoRes.java
- src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
> ex) #90 
GET /chat/rooms/{roomId}
- 채팅방 참가자일 경우에만 조회 가능
>
> [FEAT] 채팅방 기본 정보 조회 API

- src/main/java/com/project/catxi/CatxiApplication.java
- src/main/java/com/project/catxi/chat/repository/ChatRoomRepository.java
- src/main/java/com/project/catxi/chat/service/ChatRoomCleaner.java
> [FEAT] 스케줄링으로 인한 매일 정각 삭제

- src/main/java/com/project/catxi/chat/dto/ChatRoomInfoRes.java
- src/main/java/com/project/catxi/chat/dto/ChatRoomRes.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
> [CHORE] jackson timezone 어노테이션 지정

- src/main/java/com/project/catxi/chat/domain/ChatMessage.java
- src/main/java/com/project/catxi/chat/service/ChatMessageService.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/common/domain/MessageType.java
> #111 
> 강퇴하기, 나가기, 참여하기 하는 경우 실시간으로 채팅방에 시스템 메시지를 출력합니다.
>
> [FEAT] 실시간으로 강퇴, 나가기, 참여 시스템메시지 전송 구현

- src/main/java/com/project/catxi/chat/config/StompWebSocketConfig.java
- src/main/java/com/project/catxi/chat/domain/ChatMessage.java
- src/main/java/com/project/catxi/chat/service/ChatMessageService.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/chat/service/RedisPubSubService.java
- src/main/java/com/project/catxi/common/domain/MessageType.java
> [REFACT] 실시간 강퇴하기로 수정

- src/main/java/com/project/catxi/chat/dto/ParticipantsUpdateMessage.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
- src/main/java/com/project/catxi/chat/service/RedisPubSubService.java
> [FEAT] 실시간 참여자수 반영

- .gitignore
- src/main/java/com/project/catxi/common/config/security/SecurityConfig.java
- src/main/java/com/project/catxi/common/jwt/JwtFilter.java
> #130 
> /api 컨트롤러 경로 수정하면서 인증 경로도 수정하였습니다
>
> [BUGFIX] 로그인 필터 인증 허용

- src/main/java/com/project/catxi/common/auth/controller/BlacklistController.java
- src/main/java/com/project/catxi/common/auth/service/OAuthLoginService.java
- src/main/java/com/project/catxi/common/auth/service/TokenService.java
- src/main/java/com/project/catxi/common/config/security/SecurityConfig.java
- src/main/java/com/project/catxi/common/jwt/JwtTokenProvider.java
- src/main/java/com/project/catxi/common/jwt/JwtUtil.java
- src/main/java/com/project/catxi/member/controller/MemberController.java
- src/main/java/com/project/catxi/member/dto/CustomUserDetails.java
- src/main/resources/application.yml
> #135 
> ROLE 기본 값 = ROLE_USER
admin 부여시 ROLE_ADMIN에 대해 /admin 접근 가능
ROLE_USER로 접근
ROLE_ADMIN으로 접근
> 추가적인 권한 제어 관련 사항 있으면 알려주세요:)
> [FEAT] /admin 권한 제어

- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/v1.0/009-fix-report-nullable-constraints.xml
> [FEAT] DB 마이그레이션

- src/main/java/com/project/catxi/chat/controller/ChatController.java
- src/main/java/com/project/catxi/chat/repository/ChatRoomRepositoryCustomImpl.java
- src/main/java/com/project/catxi/chat/service/ChatRoomService.java
> [FIX] 채팅방 목록 조회 ETC 조건 제거 + 전체 조회 쿼리 수정

- src/main/java/com/project/catxi/chat/controller/StompController.java
- src/main/java/com/project/catxi/map/controller/MapController.java
- src/main/java/com/project/catxi/map/dto/CoordinateReq.java
- src/main/java/com/project/catxi/map/dto/CoordinateRes.java
- src/main/java/com/project/catxi/map/dto/MapInfoRes.java
- src/main/java/com/project/catxi/map/service/CoordinateProvider.java
- src/main/java/com/project/catxi/map/service/MapService.java
> ex) #141 
- MapService, CoordinateProvider 분리
- CoordinateRes와 CoordinateReq에 name, nickname 필드 추가
- 출발지 좌표가 서버에 존재하지 않을 경우 distance에는 null으로 할당되어 응답하도록 처리
- distance 단위 km로 변경
>
> [FIX] distance 계산/지도 응답 로직 수정

- src/main/java/com/project/catxi/chat/config/StompEventListener.java
- src/main/java/com/project/catxi/chat/service/ChatMessageService.java
- src/main/java/com/project/catxi/chat/service/ReadyService.java
- src/main/java/com/project/catxi/fcm/dto/FcmNotificationEvent.java
- src/main/java/com/project/catxi/fcm/service/FcmActiveStatusService.java
- src/main/java/com/project/catxi/fcm/service/FcmNotificationService.java
- src/main/java/com/project/catxi/fcm/service/FcmQueueConsumer.java
- src/main/java/com/project/catxi/fcm/service/FcmQueueService.java
- src/main/java/com/project/catxi/fcm/service/FcmTokenService.java
- src/main/java/com/project/catxi/fcm/util/FcmBusinessKeyGenerator.java
> #170 
> FCM의 로깅을 완화시켰고, 성공 여부는 프론트에서도 로깅 처리가 돼있어서 굳이 백엔드에서는 관리할 필요가 없고, 에러 로그는 그대로 유지.
>
> [REFACTOR] 불필요 로직 및 과도한 로깅 제거
